{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  # Root password (base64): foobars
  # echo -n 'dlatl!00' | base64
  password: {{.Values.secret.string}}
{{- end }}