{{- if .Values.targetGroupBinding.enabled -}}
apiVersion: v1
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "springshop.fullname" . }}-tgb
spec:
  serviceRef:
    name: {{ include "springshop.fullname" . }}
    port: {{ .Values.targetGroupBinding.ports.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
{{- end }}
