{{- if .Values.targetGroupBinding.enabled -}}
apiVersion: v1
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "springmysql.fullname" . }}-tgb
spec:
  ipAddressType: ipv4
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: {{ .Values.targetGroupBinding.from.securityGroup }}
      ports:
      - port: {{ .Values.targetGroupBinding.ports.port }}
        protocol: {{ .Values.targetGroupBinding.ports.protocol }}
  serviceRef:
    name: {{ include "springmysql.fullname" . }}
    port: {{ .Values.targetGroupBinding.ports.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
  targetType: {{ .Values.targetGroupBinding.targetType }}
{{- end }}
