# Default values for springmysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: taeeyoul/springmysql
  pullPolicy: Always # IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.1.0"

aws:
  region: ap-northeast-2
  eks:
    clusterName: "sksh-argos-d-oss-ui-01"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

initContainer:
  enabled: true
  name: gitmysql
  script: |
    #!/bin/sh

    # GitHub 저장소 클론
    git clone https://github.com/SEOTAEEYOUL/item.git /data

    # MySQL에 데이터 로딩
    for sql_file in /data/dump/*.sql; do
      filename=$(basename "$sql_file")
      mysql -h $DB_CONNECTION -u $DB_USERNAME -p $DB_PASSWORD -D $DATABASE < "$sql_file"
    done

persistent:
  use: true
  pvc: "efs-sc-pvc"
  mountPath: "/data"


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

targetGroupBinding:
  enabled: false
  from:
    securityGroup: ""
  ports:
    port: http
    protocol: TCP
  targetGroupARN: ""
  targetType: ip

ingress:
  enabled: true
  className: "alb"
  annotations: {}


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80 

nodeSelector: {}

tolerations: []

affinity: {}


secret:
  enabled: false
  name: "aurora-mysql-secret"
  string: "ZGxhdGwhMDA="

db:
  user: "tutorial"
  database: "tutorial"
  password: "aurora-mysql-secret"
  driver: "software.aws.rds.jdbc.mysql.Driver"
  connection: "jdbc:mysql:aws://rds-skcc-07456-p-aurora-mysql.cluster-cgxth7zggvw1.ap-northeast-2.rds.amazonaws.com:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
  port: 3306
  timezone: "Asia/Seoul"
    