apiVersion: v1
kind: Service
metadata:
  name: {{ include "springmysql.fullname" . }}
  labels:
    {{- include "springmysql.labels" . | nindent 4 }}
  annotations:
   prometheus.io/scrape: 'true'
   prometheus.io/port: "8090"  
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: jmx-exporter
      port: 8090
      protocol: TCP
      targetPort: 8090
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "springmysql.selectorLabels" . | nindent 4 }}
